---
- hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Only update if cache is older than 1 hour
      
    - name: Upgrade all packages
      apt:
        upgrade: yes
        force_apt_get: yes      # Use apt-get instead of aptitude for better stability
        dpkg_options: 'force-confdef,force-confold'  # Handle config file conflicts
      register: upgrade_result
      
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required
      
    - name: Notify if reboot is required
      debug:
        msg: "System requires a reboot"
      when: reboot_required.stat.exists

    - name: Clean up unused packages
      apt:
        autoremove: yes
        autoclean: yes
